### ISSUE TITLE
Will cuda support come?

### ISSUE THREAD

**Issue by kadirnar** [remydubois/lsnms#10]
I want to use lsnms library for Yolo models. But it doesn't work when cuda is active.

Error Message: 

```
I want to use lsnms library for Yolo models. But it doesn't work when cuda is active.
```

**Comment by remydubois** [comment]
Jitclasses are not supported on CUDA yet, as numba's doc states:

> Support for jitclasses are available on CPU only. (Note: Support for GPU devices is planned for a future release.)

I will port the implementation on CUDA as soon as jitclass kernels can be implemented
