### ISSUE TITLE
Update to be compatible with numpy >=1.24

### ISSUE THREAD

**Issue by chottAA5208** [remydubois/lsnms#17]
Hey Remy! I continue to use and love your library. Any chance we (or you) could fork it to make it work with a later version of numpy that we need to support? 

Thanks!

**Comment by remydubois** [comment]
Hi,

I think Numba´s latest version is built upon Numpy 1.24 and above, but I need to make sure it doesn’t break anything.  
It should be quite straightforward to update, I eventually expect a few typing issues but nothing dramatic.  

I will look into it in the coming days

**Comment by remydubois** [comment]
Hi,

I started a PR but am having some issues with github runners for the CI. [Pr is here](https://github.com/remydubois/lsnms/pull/18). I think it's not a huge deal but I don't have lot of availability to work on it those days, sorry. I will keep you posted once it's fixed.

**Comment by remydubois** [comment]
Hi, 

[This PR](https://github.com/remydubois/lsnms/pull/18) should have resolved the issue, I'm closing it. Version 0.4.0 is deployed on pypi as well, feel free to re-open if needed.

Rémy

**Comment by chottAA5208** [comment]
Much appreciated Remy!
________________________________
