### ISSUE TITLE
Issue with Score Thresholding in _nms 

### ISSUE THREAD

**Issue by chottAA5208** [remydubois/lsnms#19]
Hey Remy! Found small bug in your code that should be an easy fix! 

In the `return np.array(keep)` in line 74 of lsnms.nms.py keep is in relation to the subsetted scores/boxes of by the score_threshold score. However, in the end, it needs to refer to the full scores/boxes np.arrays provided as inputs. 

if this line is changed to `return np.argwhere(score_mask)[keep]` the correct indices of the original (unsubsetted) np.arrays will be returned.  

For an example input for which this fails and for which this fix will successfully pass is: 

`    'nms_test_dict': ( 
        #boxes 
        np.array(
            [
                [ 11.485742568969727, 15.995068550109863, 1053.8431396484375, 1074.7838134765625], 
                [ 11.485742568969727, 15.995068550109863, 1053.8431396484375, 1074.7838134765625], 
                [ 623.4799194335938, 391.9401550292969, 675.8385009765625, 445.08367919921875], 
            ]
        ),
        #scores 
        np.array([0.054, 0.154, 0.034]),
        #labels 
        np.array([1, 27, 23]),
        #score threshold 
        0.1,
        # total to keep  
        1, 
    ), `

**Comment by remydubois** [comment]
Hi,

You are absolutely right. I am sorry for the bug, I poorly designed [the related test](https://github.com/remydubois/lsnms/blob/e3daad82b7a2415d2f4ac6e23382052092d09dfd/tests/test_nms.py#L10) which made it pass.

Feel to open a PR for that, or I’ll do it in a day or two.

**Comment by chottAA5208** [comment]
Thanks Remy!

See  https://github.com/remydubois/lsnms/pull/20.

Again, thanks for the great repo. We have greatly appreciated the speedups this has provided to our codebase.
________________________________

**Comment by remydubois** [comment]
Hi, 

so sorry for the inactivity on this, I'm having little bandwidth those days. 

If this fix is critical for you, I suggest you just filter boxes on your side, before feeding them to `lsnms.nms`, and use your snippet to retrieve original indices:
```python
from lsnms import nms
import numpy as np

score_mask , *_ = np.where(scores > threshold)

filtered_idxs = nms(boxes=boxes[score_mask], scores=scores[score_mask], score_threshold=0.)

keep = score_mask[filtered_idxs]
```

I edited your [PR](https://github.com/remydubois/lsnms/pull/21) with comments to make compilation pass (although test still need to be fixed I think).
