### ISSUE TITLE
Remove numpy lock

### ISSUE THREAD

**Issue by henryruhs** [remydubois/lsnms#22]
Hey, I did actual consider using your library until the dependency tree could not be resolved as of your lock of `numpy` to `1.24.0`.

Please release a new version using `>=1.24.0` or similar. Thanks

**Comment by remydubois** [comment]
Hey,

Version 0.4.2  (released on pypi) should resolve the issue. Let me know if it works as expected.

**Comment by henryruhs** [comment]
Thanks

**Comment by henryruhs** [comment]
@remydubois Now `numba 0.57.1 depends on numpy<1.25 and >=1.21` strikes me...

**Comment by remydubois** [comment]
Thanks for reporting.

I assume you are installing `lsnms` in an existing env. If yes, what Numpy version is already installed / imposed by other libs ?

**Comment by henryruhs** [comment]
@remydubois I wanted to integrate your library to FaceFusion, but the pip dependency resolution are so bad that this worries me too much to get thousands of bug reports.

I stick to [this](https://github.com/facefusion/facefusion/blob/next/facefusion/face_helper.py#L98-L119) naive copy of InsightFace for the moment as the performance differences are not noticable. We could probably work something out on our [Discord](https://join.facefusion.io) - feel free reach out.
